In [2]:
import pickle
import numpy as np

### About libraries
Numpy is a very useful python library. Using [NumPy](http://cs231n.github.io/python-numpy-tutorial/), mathematical and logical operations on arrays can be performed.
<br>The [pickle](https://www.youtube.com/watch?v=2Tw39kZIbhs) module implements a fundamental, but powerful algorithm for serializing and de-serializing a Python object structure.

In [6]:
## Code to load the array
with open('array.pickle', 'rb') as p:
    arr = pickle.load(p)

### Task 1: Write the code and check the size of the array

In [5]:
## BEGIN CODE
print(len(arr))
## END CODE

1000


Check that the size of the array (arr) is 1000. Please report in case fo any discrepancy.

### Task 2: Resize the array to a (40x50) matrix

In [17]:
## BEGIN CODE
a = np.resize(arr,(20,50))
## END CODE

### Task 3: Find the transpose of this matrix

In [18]:
## BEGIN CODE
b = a.transpose()
## END CODE

### Task 3: Find the dot product of the matrices created in Tasks 2 & 3

In [20]:
## BEGIN CODE
c = np.dot(a,b)
## END CODE

### Task 4: Find the row wise sum of the resulting matrix

In [21]:
## BEGIN CODE
c.sum(axis=1)
## END CODE

array([2365442.27809957, 3002112.3995789 , 2779184.43777157,
       2477210.32440039, 2627759.87742664, 2220803.79590608,
       2429710.18283941, 2508044.22721641, 2459318.36600334,
       2325031.07739166, 2896081.10050922, 2762062.07921721,
       2660473.74582437, 2141287.18395127, 2694809.41626161,
       2254508.32241154, 2480788.07237605, 2727792.51946167,
       2586794.20382212, 2681242.33967484])

### Task 5: Find the cube root of all elements in the resulting matrix

In [22]:
## BEGIN CODE
np.cbrt(c)
## END CODE

array([[52.7582459 , 51.35753819, 51.23435136, 48.29779307, 48.44113667,
        45.42163648, 49.52570225, 47.34349003, 47.69166577, 46.09982687,
        50.89835315, 49.7275637 , 49.01208237, 46.79871097, 51.11656915,
        48.19459721, 48.1686254 , 50.25104429, 48.49718073, 49.4993317 ],
       [51.35753819, 59.5900052 , 54.02159437, 52.20550264, 53.19070466,
        50.57642744, 52.86389711, 51.93420282, 51.69708644, 51.20739439,
        55.74326309, 54.05943003, 53.14433173, 49.74151993, 53.88001108,
        50.1709808 , 52.91431042, 55.85856445, 53.21658758, 53.69155336],
       [51.23435136, 54.02159437, 58.31037566, 51.93658767, 51.0525514 ,
        47.88038021, 51.05695889, 51.01778143, 50.50289357, 49.36839449,
        54.04867149, 51.40990692, 53.35665416, 49.17402095, 52.13119179,
        49.00721065, 50.61849711, 53.24717747, 52.31169065, 52.302063  ],
       [48.29779307, 52.20550264, 51.93658767, 53.98545235, 49.19379837,
        47.43719677, 49.61556778, 49.99867595, 4

### Task 6: Find the sine,cos and tan-1 value of all elements in the resulting matrix

In [30]:
## BEGIN CODE(1 line of code for each)
#for sine
d=np.sin(c)
#for cos
np.cos(c)
#for tan-1
np.arctan(c)
## END CODE

array([[1.57078952, 1.57078894, 1.57078889, 1.57078745, 1.57078753,
        1.57078566, 1.57078809, 1.5707869 , 1.57078711, 1.57078612,
        1.57078874, 1.57078819, 1.57078783, 1.57078657, 1.57078884,
        1.57078739, 1.57078738, 1.57078845, 1.57078756, 1.57078808],
       [1.57078894, 1.5707916 , 1.57078998, 1.5707893 , 1.57078968,
        1.5707886 , 1.57078956, 1.57078919, 1.57078909, 1.57078888,
        1.57079055, 1.57079   , 1.57078966, 1.5707882 , 1.57078993,
        1.57078841, 1.57078958, 1.57079059, 1.57078969, 1.57078987],
       [1.57078889, 1.57078998, 1.57079128, 1.57078919, 1.57078881,
        1.57078722, 1.57078881, 1.5707888 , 1.57078856, 1.57078802,
        1.57078999, 1.57078897, 1.57078974, 1.57078792, 1.57078927,
        1.57078783, 1.57078862, 1.5707897 , 1.57078934, 1.57078934],
       [1.57078745, 1.5707893 , 1.57078919, 1.57078997, 1.57078793,
        1.57078696, 1.57078814, 1.57078833, 1.5707875 , 1.57078713,
        1.57078905, 1.57078839, 1.5707876 , 1

# Bonus Task

### Normalizing rows

Normalization is a common technique we use in Machine Learning and Deep Learning is to normalize our data. Here, by normalization we mean changing x to $ \frac{x}{\| x\|} $ (dividing each row vector of x by its norm).

For example, if $$x = 
\begin{bmatrix}
    0 & 3 & 4 \\
    2 & 6 & 4 \\
\end{bmatrix}\tag{1}$$ then $$\| x\| = np.linalg.norm(x, axis = 1, keepdims = True) = \begin{bmatrix}
    5 \\
    \sqrt{56} \\
\end{bmatrix}\tag{2} $$and        $$ x\_normalized = \frac{x}{\| x\|} = \begin{bmatrix}
    0 & \frac{3}{5} & \frac{4}{5} \\
    \frac{2}{\sqrt{56}} & \frac{6}{\sqrt{56}} & \frac{4}{\sqrt{56}} \\
\end{bmatrix}\tag{3}$$ Note that you can divide matrices of different sizes and it works fine: this is called broadcasting and you're going to learn about it in part 3.


**Exercise**: Implement normalizeRows() to normalize the rows of a matrix . After applying this function to an input matrix x, each row of x should be a vector of unit length (meaning length 1).

In [28]:
def normalizeRows(x):
    """
    Implement a function that normalizes each row of the matrix x (to have unit length).
    
    Argument:
    x -- A numpy matrix of shape (n, m)
    
    Returns:
    x -- The normalized (by row) numpy matrix. You are allowed to modify x.
    """
    
    #Begin Here(≈ 2 lines of code)
    # Compute x_norm as the norm 2 of x. Use np.linalg.norm(..., ord = 2, axis = ..., keepdims = True)
    x_norm = 𝑛𝑝.𝑙𝑖𝑛𝑎𝑙𝑔.𝑛𝑜𝑟𝑚(𝑥,𝑎𝑥𝑖𝑠=1,𝑘𝑒𝑒𝑝𝑑𝑖𝑚𝑠=𝑇𝑟𝑢𝑒)
    

    # Divide x by its norm.
    x_normf = x/x_norm
    
    #END CODE

    return x_normf

In [29]:
x = np.array([
    [0, 5, 7],
    [7, 3, 4]])
print("normalizeRows(x) = " + str(normalizeRows(x)))

normalizeRows(x) = [[0.         0.58123819 0.81373347]
 [0.81373347 0.34874292 0.46499055]]


## Create submission file

In [33]:
## Assign the name of the variable containing the final matrix of Task6 to VARIABLE_NAME variable.

VARIABLE_NAME = d
with open('submission.pickle', 'wb') as p:
    pickle.dump(VARIABLE_NAME, p)

**Expected Output**: 

<table style="width:60%">

   <tr> 
       <td> normalizeRows(x) </td> 
       <td> [[0.          0.58123819  0.81373347]
 <br>[0.81373347  0.34874292  0.46499055]</td> 
     </tr>
    
   
</table>