In [1]:
import pickle
import numpy as np

### About libraries
Numpy is a very useful python library. Using [NumPy](http://cs231n.github.io/python-numpy-tutorial/), mathematical and logical operations on arrays can be performed.
<br>The [pickle](https://www.youtube.com/watch?v=2Tw39kZIbhs) module implements a fundamental, but powerful algorithm for serializing and de-serializing a Python object structure.

In [2]:
## Code to load the array
with open('array.pickle', 'rb') as p:
    arr = pickle.load(p)

### Task 1: Write the code and check the size of the array

In [3]:
## BEGIN CODE
arr.size
## END CODE

1000

Check that the size of the array (arr) is 1000. Please report in case fo any discrepancy.

### Task 2: Resize the array to a (40x50) matrix

In [4]:
## BEGIN CODE
a = np.resize(arr, (20, 50))
a
## END CODE

array([[1.53725789e+01, 5.73068830e+01, 5.61011700e+01, 9.61243794e+01,
        8.80063242e+01, 4.62542985e+01, 7.75316736e+01, 8.33290199e+01,
        7.69185569e+01, 4.77114105e+01, 5.34745913e+01, 2.73377482e+01,
        9.22106818e+00, 1.21061938e+01, 6.13161255e+01, 1.81663623e+01,
        9.73842640e+01, 2.33789835e+01, 9.53934140e+01, 7.66998184e+01,
        1.07310147e+01, 4.71226133e+01, 1.66256417e+01, 1.68225020e+01,
        1.31450065e+01, 3.98472441e+01, 3.78902156e+01, 3.42263779e+01,
        1.56527380e+01, 2.08628772e+01, 4.07045332e+01, 1.09463141e+01,
        6.40602052e+01, 4.54751147e+01, 5.79274773e+01, 3.83884416e+01,
        7.76348596e+01, 6.40614786e+01, 6.09322132e+00, 8.99064330e+01,
        3.24397797e+00, 8.32546156e+01, 4.61723916e+00, 3.95815322e+01,
        8.36478877e+01, 7.83755760e+01, 3.27949714e+01, 6.72182919e+01,
        1.12170433e+01, 2.46297923e+01],
       [8.85893454e+01, 2.64178537e+01, 3.31570155e+01, 5.72144765e+01,
        6.77169093e+01,

### Task 3: Find the transpose of this matrix

In [5]:
## BEGIN CODE
a_t = a.T
a_t
## END CODE

array([[1.53725789e+01, 8.85893454e+01, 2.79538231e+00, 3.50908490e+01,
        8.13734157e+01, 2.98111025e+00, 3.06105570e+01, 2.46762031e+01,
        7.13226402e+00, 4.36998894e+01, 5.32027734e+01, 7.85991422e+01,
        6.93028591e+01, 7.60843419e+00, 3.52261295e+01, 5.91031443e+01,
        1.21550180e+01, 8.81098046e+01, 9.91893868e+01, 6.63677472e+01],
       [5.73068830e+01, 2.64178537e+01, 7.56172871e+01, 3.61285123e+01,
        8.14788418e+01, 2.84959605e+01, 9.13570944e+01, 8.05941652e+01,
        5.55331014e+01, 2.80522135e+01, 8.86534621e+01, 6.64995393e+01,
        2.47804763e+01, 5.83531187e+01, 4.93301355e+01, 8.22733703e+01,
        1.74234198e+01, 1.15227103e+01, 6.93302630e-02, 8.77094315e+01],
       [5.61011700e+01, 3.31570155e+01, 4.09169304e+01, 3.17348588e+01,
        5.90997317e+01, 6.22950678e+01, 2.20808491e+01, 1.04420330e+01,
        1.15857224e+00, 9.06468173e-01, 7.01084933e+01, 2.23376075e+01,
        9.21788852e+01, 3.60195634e+01, 6.10294454e+00, 9.7504

### Task 3: Find the dot product of the matrices created in Tasks 2 & 3

In [6]:
## BEGIN CODE
ans = a.dot(a_t)
ans
## END CODE

array([[146849.01683828, 135460.4747245 , 134488.05934036,
        112663.14213183, 113669.24514769,  93710.51654169,
        121476.40392393, 106115.98487967, 108474.45459776,
         97971.07721241, 131859.42941356, 122967.8407579 ,
        117736.0507943 , 102494.76239164, 133562.66968841,
        111942.51630097, 111761.63810227, 126892.30150792,
        114064.23128039, 121282.46252407],
       [135460.4747245 , 211602.24444005, 157652.98313366,
        142281.63422162, 150489.85768771, 129373.2375846 ,
        147733.00373515, 140074.92838042, 138165.0514419 ,
        134275.8882438 , 173211.67578061, 157984.46631436,
        150096.59871898, 123071.40401045, 156416.66757068,
        126286.74620133, 148156.06078107, 174288.73215696,
        150709.65242627, 154781.09202476],
       [134488.05934036, 157652.98313366, 198261.10301209,
        140094.22623001, 133061.48124711, 109767.24679661,
        133095.94676457, 132789.7968447 , 128809.76423868,
        120322.54551324, 1578

### Task 4: Find the row wise sum of the resulting matrix

In [7]:
## BEGIN CODE
row_wise_sum = np.sum(ans, axis=1)
row_wise_sum
## END CODE

array([2365442.27809957, 3002112.3995789 , 2779184.43777157,
       2477210.32440039, 2627759.87742664, 2220803.79590608,
       2429710.18283941, 2508044.22721641, 2459318.36600334,
       2325031.07739166, 2896081.10050922, 2762062.07921721,
       2660473.74582437, 2141287.18395127, 2694809.41626161,
       2254508.32241154, 2480788.07237605, 2727792.51946167,
       2586794.20382212, 2681242.33967484])

### Task 5: Find the cube root of all elements in the resulting matrix

In [8]:
## BEGIN CODE
cube_root = np.cbrt(ans)
cube_root
## END CODE

array([[52.7582459 , 51.35753819, 51.23435136, 48.29779307, 48.44113667,
        45.42163648, 49.52570225, 47.34349003, 47.69166577, 46.09982687,
        50.89835315, 49.7275637 , 49.01208237, 46.79871097, 51.11656915,
        48.19459721, 48.1686254 , 50.25104429, 48.49718073, 49.4993317 ],
       [51.35753819, 59.5900052 , 54.02159437, 52.20550264, 53.19070466,
        50.57642744, 52.86389711, 51.93420282, 51.69708644, 51.20739439,
        55.74326309, 54.05943003, 53.14433173, 49.74151993, 53.88001108,
        50.1709808 , 52.91431042, 55.85856445, 53.21658758, 53.69155336],
       [51.23435136, 54.02159437, 58.31037566, 51.93658767, 51.0525514 ,
        47.88038021, 51.05695889, 51.01778143, 50.50289357, 49.36839449,
        54.04867149, 51.40990692, 53.35665416, 49.17402095, 52.13119179,
        49.00721065, 50.61849711, 53.24717747, 52.31169065, 52.302063  ],
       [48.29779307, 52.20550264, 51.93658767, 53.98545235, 49.19379837,
        47.43719677, 49.61556778, 49.99867595, 4

### Task 6: Find the sine,cos and tan-1 value of all elements in the resulting matrix

In [9]:
## BEGIN CODE(1 line of code for each)
#for sine
sine = np.sin(ans)
print(sine)
#for cos
cosine = np.cos(ans)
print(cosine)
#for tan-1
tan_1 = np.arctan(ans)
print(tan_1)
## END CODE

[[-9.99812508e-01  9.58782809e-01  3.71447112e-01 -6.08057276e-01
   1.39301003e-01  5.07004885e-02 -4.26651890e-01 -6.68189992e-01
   9.99626239e-01 -4.88447958e-01  4.81668025e-01 -3.69888415e-01
   9.88209546e-01 -2.97495470e-01  8.41262202e-01  9.59962483e-01
   4.97356656e-01 -2.30544066e-01 -6.55455922e-01 -9.57478673e-01]
 [ 9.58782809e-01 -2.67943181e-01  9.99952030e-01 -8.89869693e-01
   9.59829930e-01  6.36138269e-01  3.80928133e-01 -6.71873084e-01
  -8.12326148e-01 -8.80367612e-01  3.51678053e-02  5.49229898e-02
  -6.64263738e-01  4.69031564e-01  8.89412237e-02  8.44007712e-01
  -9.92563075e-01 -5.18485552e-01  9.20613308e-01  8.93539497e-01]
 [ 3.71447112e-01  9.99952030e-01  9.95302384e-01 -9.26509787e-01
   6.25362264e-01 -5.19821870e-04 -6.94408390e-01  8.18366441e-01
  -9.69663111e-01 -4.37772130e-01 -1.54889240e-03  9.85091656e-01
   4.85673999e-01 -7.09977926e-01  9.96644594e-01 -9.23522781e-01
  -9.18936738e-01 -4.43071054e-01  9.71625236e-01 -9.70024315e-01]
 [-6.08

# Bonus Task

### Normalizing rows

Normalization is a common technique we use in Machine Learning and Deep Learning is to normalize our data. Here, by normalization we mean changing x to $ \frac{x}{\| x\|} $ (dividing each row vector of x by its norm).

For example, if $$x = 
\begin{bmatrix}
    0 & 3 & 4 \\
    2 & 6 & 4 \\
\end{bmatrix}\tag{1}$$ then $$\| x\| = np.linalg.norm(x, axis = 1, keepdims = True) = \begin{bmatrix}
    5 \\
    \sqrt{56} \\
\end{bmatrix}\tag{2} $$and        $$ x\_normalized = \frac{x}{\| x\|} = \begin{bmatrix}
    0 & \frac{3}{5} & \frac{4}{5} \\
    \frac{2}{\sqrt{56}} & \frac{6}{\sqrt{56}} & \frac{4}{\sqrt{56}} \\
\end{bmatrix}\tag{3}$$ Note that you can divide matrices of different sizes and it works fine: this is called broadcasting and you're going to learn about it in part 3.


**Exercise**: Implement normalizeRows() to normalize the rows of a matrix . After applying this function to an input matrix x, each row of x should be a vector of unit length (meaning length 1).

In [10]:
def normalizeRows(x):
    """
    Implement a function that normalizes each row of the matrix x (to have unit length).
    
    Argument:
    x -- A numpy matrix of shape (n, m)
    
    Returns:
    x -- The normalized (by row) numpy matrix. You are allowed to modify x.
    """
    
    #Begin Here(≈ 2 lines of code)
    # Compute x_norm as the norm 2 of x. Use np.linalg.norm(..., ord = 2, axis = ..., keepdims = True)
    x_norm = np.linalg.norm(x, ord=2, axis=1, keepdims=True)
    
    # Divide x by its norm.
    x_normf = np.divide(x, x_norm)
    
    #END CODE

    return x_normf

In [11]:
x = np.array([
    [0, 5, 7],
    [7, 3, 4]])
print("normalizeRows(x) = " + str(normalizeRows(x)))

normalizeRows(x) = [[0.         0.58123819 0.81373347]
 [0.81373347 0.34874292 0.46499055]]


**Expected Output**: 

<table style="width:60%">

   <tr> 
       <td> normalizeRows(x) </td> 
       <td> [[0.          0.58123819  0.81373347]
 <br>[0.81373347  0.34874292  0.46499055]</td> 
     </tr>
    
   
</table>

## Create submission file

In [12]:
## Assign the name of the variable containing the final matrix of Task6 to VARIABLE_NAME variable.

VARIABLE_NAME = sine
with open('submission.pickle', 'wb') as p:
    pickle.dump(VARIABLE_NAME, p)