In [2]:
import pickle
import numpy as np

### About libraries
Numpy is a very useful python library. Using [NumPy](http://cs231n.github.io/python-numpy-tutorial/), mathematical and logical operations on arrays can be performed.
<br>The [pickle](https://www.youtube.com/watch?v=2Tw39kZIbhs) module implements a fundamental, but powerful algorithm for serializing and de-serializing a Python object structure.

In [4]:
## Code to load the array
with open('C:/Users/lenovo/csoc-ml2k19-assignment-1a/Assignment_1_a/array.pickle', 'rb') as p:
    arr = pickle.load(p)

### Task 1: Write the code and check the size of the array

In [8]:
## BEGIN
arr.size
## END CODE

1000

Check that the size of the array (arr) is 1000. Please report in case fo any discrepancy.

### Task 2: Resize the array to a (20x50) matrix

In [18]:
## BEGIN CODE
arr1=arr.reshape([20,50])
arr1
## END CODE

array([[1.53725789e+01, 5.73068830e+01, 5.61011700e+01, 9.61243794e+01,
        8.80063242e+01, 4.62542985e+01, 7.75316736e+01, 8.33290199e+01,
        7.69185569e+01, 4.77114105e+01, 5.34745913e+01, 2.73377482e+01,
        9.22106818e+00, 1.21061938e+01, 6.13161255e+01, 1.81663623e+01,
        9.73842640e+01, 2.33789835e+01, 9.53934140e+01, 7.66998184e+01,
        1.07310147e+01, 4.71226133e+01, 1.66256417e+01, 1.68225020e+01,
        1.31450065e+01, 3.98472441e+01, 3.78902156e+01, 3.42263779e+01,
        1.56527380e+01, 2.08628772e+01, 4.07045332e+01, 1.09463141e+01,
        6.40602052e+01, 4.54751147e+01, 5.79274773e+01, 3.83884416e+01,
        7.76348596e+01, 6.40614786e+01, 6.09322132e+00, 8.99064330e+01,
        3.24397797e+00, 8.32546156e+01, 4.61723916e+00, 3.95815322e+01,
        8.36478877e+01, 7.83755760e+01, 3.27949714e+01, 6.72182919e+01,
        1.12170433e+01, 2.46297923e+01],
       [8.85893454e+01, 2.64178537e+01, 3.31570155e+01, 5.72144765e+01,
        6.77169093e+01,

### Task 3: Find the transpose of this matrix

In [19]:
## BEGIN CODE
arr1.T
## END CODE

array([[1.53725789e+01, 8.85893454e+01, 2.79538231e+00, 3.50908490e+01,
        8.13734157e+01, 2.98111025e+00, 3.06105570e+01, 2.46762031e+01,
        7.13226402e+00, 4.36998894e+01, 5.32027734e+01, 7.85991422e+01,
        6.93028591e+01, 7.60843419e+00, 3.52261295e+01, 5.91031443e+01,
        1.21550180e+01, 8.81098046e+01, 9.91893868e+01, 6.63677472e+01],
       [5.73068830e+01, 2.64178537e+01, 7.56172871e+01, 3.61285123e+01,
        8.14788418e+01, 2.84959605e+01, 9.13570944e+01, 8.05941652e+01,
        5.55331014e+01, 2.80522135e+01, 8.86534621e+01, 6.64995393e+01,
        2.47804763e+01, 5.83531187e+01, 4.93301355e+01, 8.22733703e+01,
        1.74234198e+01, 1.15227103e+01, 6.93302630e-02, 8.77094315e+01],
       [5.61011700e+01, 3.31570155e+01, 4.09169304e+01, 3.17348588e+01,
        5.90997317e+01, 6.22950678e+01, 2.20808491e+01, 1.04420330e+01,
        1.15857224e+00, 9.06468173e-01, 7.01084933e+01, 2.23376075e+01,
        9.21788852e+01, 3.60195634e+01, 6.10294454e+00, 9.7504

### Task 3: Find the dot product of the matrices created in Tasks 2 & 3

In [20]:
## BEGIN CODE
np.dot(arr1,arr1.T)
## END CODE

array([[146849.01683828, 135460.4747245 , 134488.05934036,
        112663.14213183, 113669.24514769,  93710.51654169,
        121476.40392393, 106115.98487967, 108474.45459776,
         97971.07721241, 131859.42941356, 122967.8407579 ,
        117736.0507943 , 102494.76239164, 133562.66968841,
        111942.51630097, 111761.63810227, 126892.30150792,
        114064.23128039, 121282.46252407],
       [135460.4747245 , 211602.24444005, 157652.98313366,
        142281.63422162, 150489.85768771, 129373.2375846 ,
        147733.00373515, 140074.92838042, 138165.0514419 ,
        134275.8882438 , 173211.67578061, 157984.46631436,
        150096.59871898, 123071.40401045, 156416.66757068,
        126286.74620133, 148156.06078107, 174288.73215696,
        150709.65242627, 154781.09202476],
       [134488.05934036, 157652.98313366, 198261.10301209,
        140094.22623001, 133061.48124711, 109767.24679661,
        133095.94676457, 132789.7968447 , 128809.76423868,
        120322.54551324, 1578

### Task 4: Find the row wise sum of the resulting matrix

In [21]:
## BEGIN CODE
np.sum(arr1,axis=1)
## END CODE

array([2295.84010152, 2941.85425796, 2721.00698087, 2459.84566477,
       2622.2280727 , 2192.62125692, 2325.35668238, 2448.48461311,
       2409.30334583, 2314.24769708, 2846.28089322, 2671.93461349,
       2615.37788033, 2107.27040831, 2614.13745912, 2276.22640968,
       2464.98344942, 2688.25588804, 2570.76504903, 2596.74229576])

### Task 5: Find the cube root of all elements in the resulting matrix

In [22]:
## BEGIN CODE
np.cbrt(arr1)
## END CODE

array([[2.48646439, 3.85539544, 3.82816492, 4.5808336 , 4.44806673,
        3.58963838, 4.26409023, 4.36782696, 4.2528204 , 3.62694318,
        3.76746441, 3.01245739, 2.09697737, 2.29616208, 3.94328562,
        2.62879058, 4.60076018, 2.85940195, 4.56919259, 4.24878523,
        2.20570247, 3.61196158, 2.5522672 , 2.5623013 , 2.36004491,
        3.41559286, 3.35873463, 3.24678587, 2.50147849, 2.75290612,
        3.43991406, 2.22035612, 4.00125388, 3.56936752, 3.8692626 ,
        3.37339213, 4.26598107, 4.00128039, 1.82648307, 4.4798512 ,
        1.48033258, 4.36652657, 1.66517848, 3.4079839 , 4.37339119,
        4.27950543, 3.20087773, 4.06595428, 2.2385122 , 2.90951265],
       [4.45786759, 2.97828219, 3.21261348, 3.85332207, 4.07598311,
        3.04791723, 2.7812366 , 3.46195397, 4.63347912, 3.35174655,
        4.08039778, 1.87019772, 4.48251062, 4.31604642, 4.34649584,
        4.6057149 , 4.38938877, 3.75458564, 4.60167583, 3.2976089 ,
        3.36154187, 3.78851516, 4.62120587, 2.5

### Task 6: Find the sine,cos and tan-1 value of all elements in the resulting matrix

In [28]:
## BEGIN CODE(1 line of code for each)
#for sine
np.sin(arr1)
#for cos
np.cos(arr1)
#for tan-1
np.arctan(arr1)
## END CODE

array([[1.50583696e+00, 1.55334819e+00, 1.55297327e+00, 1.56039351e+00,
        1.55943400e+00, 1.54918008e+00, 1.55789909e+00, 1.55879628e+00,
        1.55779630e+00, 1.54984005e+00, 1.55209804e+00, 1.53423317e+00,
        1.46277119e+00, 1.48838109e+00, 1.55448885e+00, 1.51580503e+00,
        1.56052809e+00, 1.52804892e+00, 1.56031381e+00, 1.55775922e+00,
        1.47787684e+00, 1.54957828e+00, 1.51072065e+00, 1.51142201e+00,
        1.49486806e+00, 1.54570575e+00, 1.54441041e+00, 1.54158740e+00,
        1.50699645e+00, 1.52290096e+00, 1.54623398e+00, 1.47969425e+00,
        1.55518728e+00, 1.54880982e+00, 1.55353508e+00, 1.54475271e+00,
        1.55791623e+00, 1.55518759e+00, 1.40812962e+00, 1.55967411e+00,
        1.27177569e+00, 1.55878556e+00, 1.35751081e+00, 1.54553739e+00,
        1.55884202e+00, 1.55803794e+00, 1.54031329e+00, 1.55592052e+00,
        1.48188133e+00, 1.53021738e+00],
       [1.55950877e+00, 1.53296120e+00, 1.54064594e+00, 1.55332001e+00,
        1.55603004e+00,

# Bonus Task

### Normalizing rows

Normalization is a common technique we use in Machine Learning and Deep Learning is to normalize our data. Here, by normalization we mean changing x to $ \frac{x}{\| x\|} $ (dividing each row vector of x by its norm).

For example, if $$x = 
\begin{bmatrix}
    0 & 3 & 4 \\
    2 & 6 & 4 \\
\end{bmatrix}\tag{1}$$ then $$\| x\| = np.linalg.norm(x, axis = 1, keepdims = True) = \begin{bmatrix}
    5 \\
    \sqrt{56} \\
\end{bmatrix}\tag{2} $$and        $$ x\_normalized = \frac{x}{\| x\|} = \begin{bmatrix}
    0 & \frac{3}{5} & \frac{4}{5} \\
    \frac{2}{\sqrt{56}} & \frac{6}{\sqrt{56}} & \frac{4}{\sqrt{56}} \\
\end{bmatrix}\tag{3}$$ Note that you can divide matrices of different sizes and it works fine: this is called broadcasting and you're going to learn about it in part 3.


**Exercise**: Implement normalizeRows() to normalize the rows of a matrix . After applying this function to an input matrix x, each row of x should be a vector of unit length (meaning length 1).

In [ ]:
def normalizeRows(x):
    """
    Implement a function that normalizes each row of the matrix x (to have unit length).
    
    Argument:
    x -- A numpy matrix of shape (n, m)
    
    Returns:
    x -- The normalized (by row) numpy matrix. You are allowed to modify x.
    """
    
    #Begin Here(≈ 2 lines of code)
    # Compute x_norm as the norm 2 of x. Use np.linalg.norm(..., ord = 2, axis = ..., keepdims = True)
    
    

    # Divide x by its norm.
    
    
    #END CODE

    return x_normf

In [ ]:
x = np.array([
    [0, 5, 7],
    [7, 3, 4]])
print("normalizeRows(x) = " + str(normalizeRows(x)))

**Expected Output**: 

<table style="width:60%">

   <tr> 
       <td> normalizeRows(x) </td> 
       <td> [[0.          0.58123819  0.81373347]
 <br>[0.81373347  0.34874292  0.46499055]</td> 
     </tr>
    
   
</table>

## Create submission file

In [ ]:
## Assign the name of the variable containing the final matrix of Task6 to VARIABLE_NAME variable.

VARIABLE_NAME = 
with open('submission.pickle', 'wb') as p:
    pickle.dump(VARIABLE_NAME, p)