In [7]:
import pickle
import numpy as np

### About libraries
Numpy is a very useful python library. Using [NumPy](http://cs231n.github.io/python-numpy-tutorial/), mathematical and logical operations on arrays can be performed.
<br>The [pickle](https://www.youtube.com/watch?v=2Tw39kZIbhs) module implements a fundamental, but powerful algorithm for serializing and de-serializing a Python object structure.

In [8]:
## Code to load the array
with open('array.pickle', 'rb') as p:
    arr = pickle.load(p)

### Task 1: Write the code and check the size of the array

In [9]:
## BEGIN CODE
print(len(arr))
## END CODE

1000


Check that the size of the array (arr) is 1000. Please report in case fo any discrepancy.

### Task 2: Resize the array to a (20x50) matrix

In [10]:
## BEGIN CODE
arr = np.resize(arr,(50,20))
    
print(len(arr))
## END CODE

50


### Task 3: Find the transpose of this matrix

In [11]:
## BEGIN CODE
trans_arr = arr.transpose()
len(trans_arr)
## END CODE

20

### Task 3: Find the dot product of the matrices created in Tasks 2 & 3

In [12]:
## BEGIN CODE
dot_arr = np.dot(arr,trans_arr)
len(dot_arr)

50

### Task 4: Find the row wise sum of the resulting matrix

In [13]:
## BEGIN CODE
"""row_sum_vect = []
for elem in dot_arr:
    row_sum_vect.append(sum(elem))
"""
row_sum_vect = dot_arr.sum(axis = 1,dtype=float)
row_sum_vect
## END CODE

array([2846185.62373607, 1873594.44295737, 2361027.81018116,
       3135719.8706376 , 3019688.48419682, 3412121.71510996,
       2316122.90865746, 2564626.10042831, 2568557.87874004,
       2234424.63430471, 2428611.1360621 , 2845545.11735985,
       2148899.44868764, 2183139.86517425, 2491096.68575032,
       2995200.06825431, 1711756.7651671 , 2290418.15219147,
       2736026.36411109, 2334102.54908191, 1950720.28126986,
       2937136.56891259, 1946005.57011117, 2820954.08414548,
       2302698.0683693 , 3085843.17068601, 3001822.82195083,
       2447689.19360003, 2805692.26396518, 2568792.51088958,
       2687738.32654443, 2507306.93369412, 2532677.39717161,
       2352655.39464793, 1841966.00529172, 2777404.2635646 ,
       2419924.8314605 , 2731298.00278802, 2098973.04321894,
       2204935.4623818 , 2216275.17245887, 2523185.5960451 ,
       2641355.81627463, 2362258.28767915, 3209367.79463244,
       2789256.52514968, 2540275.10553885, 2766732.71436769,
       2877951.57663704,

### Task 5: Find the cube root of all elements in the resulting matrix

In [14]:
## BEGIN CODE
cube_root_vect = np.power(row_sum_vect, float(1/3))
cube_root_vect
## END CODE

array([141.71671394, 123.27978355, 133.15792968, 146.36786994,
       144.53977719, 150.54794726, 132.30833394, 136.8804274 ,
       136.95034126, 130.73400632, 134.41652409, 141.70608248,
       129.04426197, 129.72604766, 135.55957377, 144.14799709,
       119.62281486, 131.81705127, 139.86426238, 132.64981368,
       124.94867827, 143.21045136, 124.84793391, 141.29669571,
       132.05220747, 145.58767712, 144.25416183, 134.76757802,
       141.0414221 , 136.95451117, 139.03655382, 135.85297935,
       136.30965696, 133.00034663, 122.58214133, 140.56580992,
       134.2560788 , 139.78364546, 128.0370385 , 130.15632993,
       130.37907448, 136.13915968, 138.23212031, 133.18105794,
       147.50491673, 140.76547579, 136.44582474, 140.38554805,
       142.24199259, 127.14079607])

### Task 6: Find the sine,cos and tan-1 value of all elements in the resulting matrix

In [15]:
## BEGIN CODE(1 line of code for each)
#for sine
sin_arr =np.sin(cube_root_vect * np.pi / 180. )
#for cos
cos_arr =np.cos(cube_root_vect * np.pi / 180. )
#for tan-1
tanh_arr =np.arctan(cube_root_vect)
## END CODE
finale = [sin_arr,cos_arr,tanh_arr]
finale

[array([0.61955008, 0.83600103, 0.72947107, 0.55385854, 0.58013762,
        0.49169504, 0.73953319, 0.68352316, 0.68263197, 0.75774717,
        0.71427087, 0.61969572, 0.77665957, 0.76910908, 0.70016728,
        0.58569357, 0.86929818, 0.74527761, 0.64460062, 0.73550832,
        0.81966549, 0.59887753, 0.82067146, 0.62528766, 0.74253481,
        0.56514445, 0.58419071, 0.70996935, 0.62875839, 0.68257879,
        0.6555774 , 0.6965019 , 0.69076055, 0.73134958, 0.84262029,
        0.63519151, 0.71622791, 0.64567568, 0.7876126 , 0.76428777,
        0.76177496, 0.69290919, 0.66611445, 0.7291949 , 0.53722723,
        0.63249614, 0.68904014, 0.63761832, 0.61232778, 0.79715423]),
 array([-0.78495713, -0.54872787, -0.68401166, -0.83261078, -0.81451847,
        -0.87076747, -0.67312009, -0.72992882, -0.73076233, -0.65254826,
        -0.69986937, -0.78484216, -0.62992056, -0.63911753, -0.71397884,
        -0.81053256, -0.49428806, -0.6667543 , -0.76451949, -0.67751569,
        -0.57284246, -0.80

# Bonus Task

### Normalizing rows

Normalization is a common technique we use in Machine Learning and Deep Learning is to normalize our data. Here, by normalization we mean changing x to $ \frac{x}{\| x\|} $ (dividing each row vector of x by its norm).

For example, if $$x = 
\begin{bmatrix}
    0 & 3 & 4 \\
    2 & 6 & 4 \\
\end{bmatrix}\tag{1}$$ then $$\| x\| = np.linalg.norm(x, axis = 1, keepdims = True) = \begin{bmatrix}
    5 \\
    \sqrt{56} \\
\end{bmatrix}\tag{2} $$and        $$ x\_normalized = \frac{x}{\| x\|} = \begin{bmatrix}
    0 & \frac{3}{5} & \frac{4}{5} \\
    \frac{2}{\sqrt{56}} & \frac{6}{\sqrt{56}} & \frac{4}{\sqrt{56}} \\
\end{bmatrix}\tag{3}$$ Note that you can divide matrices of different sizes and it works fine: this is called broadcasting and you're going to learn about it in part 3.


**Exercise**: Implement normalizeRows() to normalize the rows of a matrix . After applying this function to an input matrix x, each row of x should be a vector of unit length (meaning length 1).

In [16]:
def normalizeRows(x):
    """
    Implement a function that normalizes each row of the matrix x (to have unit length).
    
    Argument:
    x -- A numpy matrix of shape (n, m)
    
    Returns:
    x -- The normalized (by row) numpy matrix. You are allowed to modify x.
    """
    
    #Begin Here(≈ 2 lines of code)
    # Compute x_norm as the norm 2 of x. Use np.linalg.norm(..., ord = 2, axis = ..., keepdims = True)
    x_norm = np.linalg.norm(x, ord = 2, axis = 1, keepdims = True)
    

    # Divide x by its norm.
    x_normf = np.divide(x , x_norm)
    
    
    #END CODE

    return x_normf

In [17]:
x = np.array([
    [0, 5, 7],
    [7, 3, 4]])
print("normalizeRows(x) = " + str(normalizeRows(x)))

normalizeRows(x) = [[0.         0.58123819 0.81373347]
 [0.81373347 0.34874292 0.46499055]]


**Expected Output**: 

<table style="width:60%">

   <tr> 
       <td> normalizeRows(x) </td> 
       <td> [[0.          0.58123819  0.81373347]
 <br>[0.81373347  0.34874292  0.46499055]</td> 
     </tr>
    
   
</table>

## Create submission file

In [18]:
## Assign the name of the variable containing the final matrix of Task6 to VARIABLE_NAME variable.

VARIABLE_NAME = finale
with open('submission.pickle', 'wb') as p:
    pickle.dump(VARIABLE_NAME, p)