In [48]:
import pickle
import numpy as np

### About libraries
Numpy is a very useful python library. Using [NumPy](http://cs231n.github.io/python-numpy-tutorial/), mathematical and logical operations on arrays can be performed.
<br>The [pickle](https://www.youtube.com/watch?v=2Tw39kZIbhs) module implements a fundamental, but powerful algorithm for serializing and de-serializing a Python object structure.

In [49]:
## Code to load the array
with open('array.pickle', 'rb') as p:
    arr = pickle.load(p)

### Task 1: Write the code and check the size of the array

In [50]:
## BEGIN CODE
arr.size
## END CODE

1000

Check that the size of the array (arr) is 1000. Please report in case fo any discrepancy.

### Task 2: Resize the array to a (20x50) matrix

In [51]:
## BEGIN CODE
arr=arr.reshape(20,50)
## END CODE

### Task 3: Find the transpose of this matrix

In [52]:
## BEGIN CODE
arr.T
## END CODE

array([[1.53725789e+01, 8.85893454e+01, 2.79538231e+00, 3.50908490e+01,
        8.13734157e+01, 2.98111025e+00, 3.06105570e+01, 2.46762031e+01,
        7.13226402e+00, 4.36998894e+01, 5.32027734e+01, 7.85991422e+01,
        6.93028591e+01, 7.60843419e+00, 3.52261295e+01, 5.91031443e+01,
        1.21550180e+01, 8.81098046e+01, 9.91893868e+01, 6.63677472e+01],
       [5.73068830e+01, 2.64178537e+01, 7.56172871e+01, 3.61285123e+01,
        8.14788418e+01, 2.84959605e+01, 9.13570944e+01, 8.05941652e+01,
        5.55331014e+01, 2.80522135e+01, 8.86534621e+01, 6.64995393e+01,
        2.47804763e+01, 5.83531187e+01, 4.93301355e+01, 8.22733703e+01,
        1.74234198e+01, 1.15227103e+01, 6.93302630e-02, 8.77094315e+01],
       [5.61011700e+01, 3.31570155e+01, 4.09169304e+01, 3.17348588e+01,
        5.90997317e+01, 6.22950678e+01, 2.20808491e+01, 1.04420330e+01,
        1.15857224e+00, 9.06468173e-01, 7.01084933e+01, 2.23376075e+01,
        9.21788852e+01, 3.60195634e+01, 6.10294454e+00, 9.7504

### Task 3: Find the dot product of the matrices created in Tasks 2 & 3

In [53]:
## BEGIN CODE
arr3=arr@(arr.T)
arr3
## END CODE

array([[146849.01683828, 135460.4747245 , 134488.05934036,
        112663.14213183, 113669.24514769,  93710.51654169,
        121476.40392393, 106115.98487967, 108474.45459776,
         97971.07721241, 131859.42941356, 122967.8407579 ,
        117736.0507943 , 102494.76239164, 133562.66968841,
        111942.51630097, 111761.63810227, 126892.30150792,
        114064.23128039, 121282.46252407],
       [135460.4747245 , 211602.24444005, 157652.98313366,
        142281.63422162, 150489.85768771, 129373.2375846 ,
        147733.00373515, 140074.92838042, 138165.0514419 ,
        134275.8882438 , 173211.67578061, 157984.46631436,
        150096.59871898, 123071.40401045, 156416.66757068,
        126286.74620133, 148156.06078107, 174288.73215696,
        150709.65242627, 154781.09202476],
       [134488.05934036, 157652.98313366, 198261.10301209,
        140094.22623001, 133061.48124711, 109767.24679661,
        133095.94676457, 132789.7968447 , 128809.76423868,
        120322.54551324, 1578

### Task 4: Find the row wise sum of the resulting matrix

In [54]:
## BEGIN CODE
arr4=arr3.sum(axis=1)
arr4
## END CODE

array([2365442.27809957, 3002112.3995789 , 2779184.43777157,
       2477210.32440039, 2627759.87742664, 2220803.79590608,
       2429710.18283941, 2508044.22721641, 2459318.36600334,
       2325031.07739166, 2896081.10050922, 2762062.07921721,
       2660473.74582437, 2141287.18395127, 2694809.41626161,
       2254508.32241154, 2480788.07237605, 2727792.51946167,
       2586794.20382212, 2681242.33967484])

### Task 5: Find the cube root of all elements in the resulting matrix

In [55]:
## BEGIN CODE
arr5=arr4**(1/3)
arr5
## END CODE

array([133.24086749, 144.25880028, 140.59583534, 135.30721666,
       137.9945366 , 130.46781737, 134.43679738, 135.86629426,
       134.98067151, 132.47774307, 142.5400499 , 140.30650668,
       138.56482338, 128.89170616, 139.15837608, 131.12453093,
       135.37232514, 139.7238181 , 137.2736853 , 138.92445112])

### Task 6: Find the sine,cos and tan-1 value of all elements in the resulting matrix

In [56]:
## BEGIN CODE(1 line of code for each)
#for sine
arr61=np.sin(arr5)
arr61
#for cos
arr62=np.sin(arr5)
arr62
#for tan-1
arr63=np.arctan(arr5)
arr63
## END CODE

array([1.56329126, 1.56386445, 1.56368386, 1.56340587, 1.56354979,
       1.56313175, 1.56335802, 1.56343628, 1.56338799, 1.56324803,
       1.56378087, 1.56366919, 1.56357961, 1.56303803, 1.56361039,
       1.56317014, 1.56340943, 1.56363947, 1.56351174, 1.56359829])

# Bonus Task

### Normalizing rows

Normalization is a common technique we use in Machine Learning and Deep Learning is to normalize our data. Here, by normalization we mean changing x to $ \frac{x}{\| x\|} $ (dividing each row vector of x by its norm).

For example, if $$x = 
\begin{bmatrix}
    0 & 3 & 4 \\
    2 & 6 & 4 \\
\end{bmatrix}\tag{1}$$ then $$\| x\| = np.linalg.norm(x, axis = 1, keepdims = True) = \begin{bmatrix}
    5 \\
    \sqrt{56} \\
\end{bmatrix}\tag{2} $$and        $$ x\_normalized = \frac{x}{\| x\|} = \begin{bmatrix}
    0 & \frac{3}{5} & \frac{4}{5} \\
    \frac{2}{\sqrt{56}} & \frac{6}{\sqrt{56}} & \frac{4}{\sqrt{56}} \\
\end{bmatrix}\tag{3}$$ Note that you can divide matrices of different sizes and it works fine: this is called broadcasting and you're going to learn about it in part 3.


**Exercise**: Implement normalizeRows() to normalize the rows of a matrix . After applying this function to an input matrix x, each row of x should be a vector of unit length (meaning length 1).

In [57]:
def normalizeRows(x):
    """
    Implement a function that normalizes each row of the matrix x (to have unit length).
    
    Argument:
    x -- A numpy matrix of shape (n, m)
    
    Returns:
    x -- The normalized (by row) numpy matrix. You are allowed to modify x.
    """
    
    #Begin Here(≈ 2 lines of code)
    # Compute x_norm as the norm 2 of x. Use np.linalg.norm(..., ord = 2, axis = ..., keepdims = True)
    x_norm=𝑛𝑝.𝑙𝑖𝑛𝑎𝑙𝑔.𝑛𝑜𝑟𝑚(𝑥,ord=2,𝑎𝑥𝑖𝑠=1,𝑘𝑒𝑒𝑝𝑑𝑖𝑚𝑠=𝑇𝑟𝑢𝑒)
    

    # Divide x by its norm.
    x_normf=x/x_norm
    
    #END CODE

    return x_normf

In [58]:
x = np.array([
    [0, 5, 7],
    [7, 3, 4]])
print("normalizeRows(x) = " + str(normalizeRows(x)))

normalizeRows(x) = [[0.         0.58123819 0.81373347]
 [0.81373347 0.34874292 0.46499055]]


**Expected Output**: 

<table style="width:60%">

   <tr> 
       <td> normalizeRows(x) </td> 
       <td> [[0.          0.58123819  0.81373347]
 <br>[0.81373347  0.34874292  0.46499055]</td> 
     </tr>
    
   
</table>

## Create submission file

In [62]:
## Assign the name of the variable containing the final matrix of Task6 to VARIABLE_NAME variable.

VARIABLE_NAME = arr63
with open('submission.pickle', 'wb') as p:
    pickle.dump(VARIABLE_NAME, p)