In [ ]:
import pickle
import numpy as np

### About libraries
Numpy is a very useful python library. Using [NumPy](http://cs231n.github.io/python-numpy-tutorial/), mathematical and logical operations on arrays can be performed.
<br>The [pickle](https://www.youtube.com/watch?v=2Tw39kZIbhs) module implements a fundamental, but powerful algorithm for serializing and de-serializing a Python object structure.

In [ ]:
## Code to load the array
with open('array.pickle', 'rb') as p:
    arr = pickle.load(p)

### Task 1: Write the code and check the size of the array

In [5]:
## BEGIN CODE
import pickle
import numpy as np
with open('array.pickle','rb') as p:
    arr = pickle.load(p)
arr.size==1000
## END CODE

True

Check that the size of the array (arr) is 1000. Please report in case fo any discrepancy.

### Task 2: Resize the array to a (20x50) matrix

In [7]:
## BEGIN CODE
import pickle
import numpy as np
with open('array.pickle','rb') as p:
    arr = pickle.load(p)
arr.reshape(50,20)
## END CODE

array([[1.53725789e+01, 5.73068830e+01, 5.61011700e+01, 9.61243794e+01,
        8.80063242e+01, 4.62542985e+01, 7.75316736e+01, 8.33290199e+01,
        7.69185569e+01, 4.77114105e+01, 5.34745913e+01, 2.73377482e+01,
        9.22106818e+00, 1.21061938e+01, 6.13161255e+01, 1.81663623e+01,
        9.73842640e+01, 2.33789835e+01, 9.53934140e+01, 7.66998184e+01],
       [1.07310147e+01, 4.71226133e+01, 1.66256417e+01, 1.68225020e+01,
        1.31450065e+01, 3.98472441e+01, 3.78902156e+01, 3.42263779e+01,
        1.56527380e+01, 2.08628772e+01, 4.07045332e+01, 1.09463141e+01,
        6.40602052e+01, 4.54751147e+01, 5.79274773e+01, 3.83884416e+01,
        7.76348596e+01, 6.40614786e+01, 6.09322132e+00, 8.99064330e+01],
       [3.24397797e+00, 8.32546156e+01, 4.61723916e+00, 3.95815322e+01,
        8.36478877e+01, 7.83755760e+01, 3.27949714e+01, 6.72182919e+01,
        1.12170433e+01, 2.46297923e+01, 8.85893454e+01, 2.64178537e+01,
        3.31570155e+01, 5.72144765e+01, 6.77169093e+01, 2.8314

### Task 3: Find the transpose of this matrix

In [10]:
## BEGIN CODE
import pickle
import numpy as np
with open('array.pickle','rb') as p:
    arr = pickle.load(p)
arr.reshape(50,20)
arrT=np.transpose(arr)
## END CODE

[1.53725789e+01 5.73068830e+01 5.61011700e+01 9.61243794e+01
 8.80063242e+01 4.62542985e+01 7.75316736e+01 8.33290199e+01
 7.69185569e+01 4.77114105e+01 5.34745913e+01 2.73377482e+01
 9.22106818e+00 1.21061938e+01 6.13161255e+01 1.81663623e+01
 9.73842640e+01 2.33789835e+01 9.53934140e+01 7.66998184e+01
 1.07310147e+01 4.71226133e+01 1.66256417e+01 1.68225020e+01
 1.31450065e+01 3.98472441e+01 3.78902156e+01 3.42263779e+01
 1.56527380e+01 2.08628772e+01 4.07045332e+01 1.09463141e+01
 6.40602052e+01 4.54751147e+01 5.79274773e+01 3.83884416e+01
 7.76348596e+01 6.40614786e+01 6.09322132e+00 8.99064330e+01
 3.24397797e+00 8.32546156e+01 4.61723916e+00 3.95815322e+01
 8.36478877e+01 7.83755760e+01 3.27949714e+01 6.72182919e+01
 1.12170433e+01 2.46297923e+01 8.85893454e+01 2.64178537e+01
 3.31570155e+01 5.72144765e+01 6.77169093e+01 2.83145399e+01
 2.15136356e+01 4.14919522e+01 9.94767596e+01 3.76542075e+01
 6.79371789e+01 6.54127749e+00 9.00666440e+01 8.04004205e+01
 8.21141128e+01 9.769923

### Task 3: Find the dot product of the matrices created in Tasks 2 & 3

In [17]:
## BEGIN CODE
import pickle
import numpy as np
with open('array.pickle','rb') as p:
    arr = pickle.load(p)
arr.reshape(50,20)
arrT=np.transpose(arr)
new_arr = np.dot(arr,arrT)
print(new_arr)
## END CODE

3343328.3330385387


### Task 4: Find the row wise sum of the resulting matrix

In [27]:
## BEGIN CODE
import pickle
import numpy as np
with open('array.pickle','rb') as p:
    arr = pickle.load(p)
arr=arr.reshape(50,20)
arrT=np.transpose(arr)
new_arr = np.dot(arr,arrT)
new_arr.sum(axis=1)
## END CODE

array([2846185.62373607, 1873594.44295737, 2361027.81018116,
       3135719.8706376 , 3019688.48419682, 3412121.71510996,
       2316122.90865746, 2564626.10042831, 2568557.87874004,
       2234424.63430471, 2428611.1360621 , 2845545.11735985,
       2148899.44868764, 2183139.86517425, 2491096.68575032,
       2995200.06825431, 1711756.7651671 , 2290418.15219147,
       2736026.36411109, 2334102.54908191, 1950720.28126986,
       2937136.56891259, 1946005.57011117, 2820954.08414548,
       2302698.0683693 , 3085843.17068601, 3001822.82195083,
       2447689.19360003, 2805692.26396518, 2568792.51088958,
       2687738.32654443, 2507306.93369412, 2532677.39717161,
       2352655.39464793, 1841966.00529172, 2777404.2635646 ,
       2419924.8314605 , 2731298.00278802, 2098973.04321894,
       2204935.4623818 , 2216275.17245887, 2523185.5960451 ,
       2641355.81627463, 2362258.28767915, 3209367.79463244,
       2789256.52514968, 2540275.10553885, 2766732.71436769,
       2877951.57663704,

### Task 5: Find the cube root of all elements in the resulting matrix

In [28]:
## BEGIN CODE
import pickle
import numpy as np
with open('array.pickle','rb') as p:
    arr = pickle.load(p)
arr=arr.reshape(50,20)
arrT=np.transpose(arr)
new_arr = np.dot(arr,arrT)
new_arr.sum(axis=1)
np.cbrt(new_arr)
## END CODE

array([[43.0673415 , 34.4276528 , 38.39936231, ..., 37.64999209,
        41.185187  , 36.21163969],
       [34.4276528 , 33.90401404, 32.74374129, ..., 35.27399045,
        34.09366918, 32.28679299],
       [38.39936231, 32.74374129, 39.10509991, ..., 37.15780085,
        37.28448018, 34.04725522],
       ...,
       [37.64999209, 35.27399045, 37.15780085, ..., 42.94359222,
        38.73893125, 34.68094212],
       [41.185187  , 34.09366918, 37.28448018, ..., 38.73893125,
        43.57393015, 34.75212677],
       [36.21163969, 32.28679299, 34.04725522, ..., 34.68094212,
        34.75212677, 35.77326823]])

### Task 6: Find the sine,cos and tan-1 value of all elements in the resulting matrix

In [ ]:
## BEGIN CODE(1 line of code for each)
import pickle
import numpy as np
with open('array.pickle','rb') as p:
    arr = pickle.load(p)
arr=arr.reshape(50,20)
arrT=np.transpose(arr)
new_arr = np.dot(arr,arrT)
new_arr.sum(axis=1)
new_arr=np.cbrt(new_arr)
#for sine
np.sin(new_arr)
#for cos
np.cos(new_arr)
#for tan-1
mp.arctan(new_arr)
## END CODE

# Bonus Task

### Normalizing rows

Normalization is a common technique we use in Machine Learning and Deep Learning is to normalize our data. Here, by normalization we mean changing x to $ \frac{x}{\| x\|} $ (dividing each row vector of x by its norm).

For example, if $$x = 
\begin{bmatrix}
    0 & 3 & 4 \\
    2 & 6 & 4 \\
\end{bmatrix}\tag{1}$$ then $$\| x\| = np.linalg.norm(x, axis = 1, keepdims = True) = \begin{bmatrix}
    5 \\
    \sqrt{56} \\
\end{bmatrix}\tag{2} $$and        $$ x\_normalized = \frac{x}{\| x\|} = \begin{bmatrix}
    0 & \frac{3}{5} & \frac{4}{5} \\
    \frac{2}{\sqrt{56}} & \frac{6}{\sqrt{56}} & \frac{4}{\sqrt{56}} \\
\end{bmatrix}\tag{3}$$ Note that you can divide matrices of different sizes and it works fine: this is called broadcasting and you're going to learn about it in part 3.


**Exercise**: Implement normalizeRows() to normalize the rows of a matrix . After applying this function to an input matrix x, each row of x should be a vector of unit length (meaning length 1).

In [ ]:
def normalizeRows(x):
    """
    Implement a function that normalizes each row of the matrix x (to have unit length).
    
    Argument:
    x -- A numpy matrix of shape (n, m)
    
    Returns:
    x -- The normalized (by row) numpy matrix. You are allowed to modify x.
    """
    
    #Begin Here(≈ 2 lines of code)
    # Compute x_norm as the norm 2 of x. Use np.linalg.norm(..., ord = 2, axis = ..., keepdims = True)
    
    

    # Divide x by its norm.
    
    
    #END CODE

    return x_normf

In [ ]:
x = np.array([
    [0, 5, 7],
    [7, 3, 4]])
print("normalizeRows(x) = " + str(normalizeRows(x)))

**Expected Output**: 

<table style="width:60%">

   <tr> 
       <td> normalizeRows(x) </td> 
       <td> [[0.          0.58123819  0.81373347]
 <br>[0.81373347  0.34874292  0.46499055]</td> 
     </tr>
    
   
</table>

## Create submission file

In [ ]:
## Assign the name of the variable containing the final matrix of Task6 to VARIABLE_NAME variable.

VARIABLE_NAME = 
with open('submission.pickle', 'wb') as p:
    pickle.dump(VARIABLE_NAME, p)